services:
  trafikinfo:
    build: .
    image: ghcr.io/minglarn/trafikinfo:latest
    container_name: trafikinfo-flux
    ports:
      - "7081:8000"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - DEBUG_MODE=true # Set to true for detailed logs
      - TZ=Europe/Stockholm
